server:
  port: 5287
  context-path: /

spring:
  profiles:
    active: @profileActive@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  http:
    multipart:
      max-file-size: 500Mb      # Max file size，默认1M
      max-request-size: 1000Mb   # Max request size，默认10M

jodconverter:
  local:
    enabled: true
    max-tasks-per-process: 10
    port-numbers: 8100
    office-home: @openOfficeHome@

security:
  user:
    name: duke
    password: duke
  basic:
    enabled: false
  oauth2:
    resource:
      service-id: duke-auth
      user-info-uri: http://127.0.0.1:5285/auth/user/duke-storage

management:
  security:
    enabled: false
  context-path: /management

logging:
  file: ./logs/storage.log
  level:
    root: info

debug: true

mybatis:
    mapper-locations: classpath*:mapper/**/*Mapper.xml
