server:
  port: 5287
  context-path: /

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/duke_storage?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: duke
    hikari:
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

security:
  user:
    name: duke
    password: duke
  basic:
    enabled: false

management:
  security:
    enabled: false
  context-path: /management

logging:
  file: ./logs/storage.log
  level:
    root: info

debug: true

duke:
  storage:
    path: D:/work/file_storage/duke
    max-upload-size: 1024
    #操作相关文件存放的根目录，此目录在初始化的时候，里面的内容会被删除
    tmp:
      root: d:/work/code/duke/blog/storage/tmp/conventer  #转换后文件存储位置
      root-temp: d:/work/code/duke/blog/storage/tmp/conventer #下载文件的临时存放位置
    #文本类型文件后缀
    text-type: txt,sql,java,js,html,xml,html,css
    #图片类型文件后缀
    img-type: jpeg,jpg,png,bmp
    #office文件类型后缀
    office-type: doc,docx,xlsx,xls,ppt,pptx
    #压缩文件类型后缀
    compress-type: zip,rar,jar,gzip
    #pdf文件
    pdf-type: pdt
    soffice:
      home: D:/app/openoffics #openofficean安装位置
      port: 8100 #openoffice链接端口
      defaultCharset: GBK #预览纯文本需要转码，windows下问GBK，linux下问UTF-8
    qiniu:
      accessKey: V2gvMcNpvtCDaIpHisRH3Yy2zTNi6KI0ZmvoW24N
      secretKey: 8uZC6BRXqHRHJ6XL-degwFVM8y_VZr6pwJSIbfJX
      bucket: duke-blog  #创建的存储空间名
      path:     #存储空间的访问域名
  sqllog:
    enabled: true #开启sqllog
  swagger:
    enabled: true #开启swagger,默认为开启
    title: storage api
    description: 存储项目服务
    version:
    termsOfServiceUrl:
    license:
    licenseUrl:
    basePackage: com.duke.microservice.storage

mybatis:
    mapper-locations: classpath*:mapper/**/*Mapper.xml